// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Piwonka.CC.Data.Piwonka.CC.Data;

#nullable disable

namespace Piwonka.CC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250510194449_Initital")]
    partial class Initital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Piwonka.CC.Models.Kategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Kategorien");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beschreibung = "Allgemeine Beiträge",
                            Name = "Allgemein"
                        },
                        new
                        {
                            Id = 2,
                            Beschreibung = "Beiträge über Technologie",
                            Name = "Technologie"
                        },
                        new
                        {
                            Id = 3,
                            Beschreibung = "Beiträge über Lifestyle",
                            Name = "Lifestyle"
                        });
                });

            modelBuilder.Entity("Piwonka.CC.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BildUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Inhalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IstVeröffentlicht")
                        .HasColumnType("bit");

                    b.Property<int?>("KategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("KategorieId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Piwonka.CC.Models.Post", b =>
                {
                    b.HasOne("Piwonka.CC.Models.Kategorie", "Kategorie")
                        .WithMany("Posts")
                        .HasForeignKey("KategorieId");

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("Piwonka.CC.Models.Kategorie", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
